### ISSUE TITLE
Package metadata directory METADATA doesn't exist

### ISSUE THREAD

**Issue by pcarbo** [JuliaLang/Pkg3.jl#103]
Following the installation instructions in the README, I encounter the following error:

```Julia
Pkg.clone("https://github.com/JuliaLang/Pkg3.jl.git")
# ERROR: Package metadata directory /tmp/pcarbo/julia/v0.6/METADATA doesn't exist; run Pkg.init() to initialize it.
```

The solution is given; however, I do not want to run `Pkg.init()` because it create the large number of small metadata files, the problem I'm seeking to avoid in the first place (because I'm running Julia on a networked filesystem on a compute cluster).

Has this issue already been addressed previously? Is there a workaround you can suggest?

**Comment by StefanKarpinski** [comment]
You can clone the Pkg3 repo directly into somewhere on your `LOAD_PATH` to use it.

**Comment by KristofferC** [comment]
For now, just navigate to someplace where you have `LOAD_PATH` to look at and do:

```
git clone https://github.com/staticfloat/SHA.jl SHA
git clone https://github.com/JuliaLang/Pkg3.jl Pkg3 
```

This should give you access to Pkg3 without using Pkg2.

**Comment by pcarbo** [comment]
@StefanKarpinski @KristofferC Thank you, it seems to work now (mostly). I would encourage you add these instructions to the README (I'm sure they will be useful to others!).

**Comment by StefanKarpinski** [comment]
The plan is to bake Pkg3 into Julia itself and you won't have to do that.
