### ISSUE TITLE
METADATA CI Controls in manifest?

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaLang/Pkg3.jl#148]
I think it would make sense to have an easy way to control some METADATA options. For example, JuliaCIBot controls. Some packages you know it's going to fail, so a way to turn it off could lower the CI load and make METADATA throw less red X's when you know it's going to fail (example: needs GPUs or some odd build). Or instead of random packages, be able to list some higher priority packages.

**Comment by KristofferC** [comment]
This seems like it should be done with some `JuliaCIBot` specific config file. Don't think the package manager has to be involved in this.

**Comment by ChrisRackauckas** [comment]
So then is an issue in METADATA more appropriate?

**Comment by KristofferC** [comment]
Cargo has a metadata section to put random stuff in. I think it warns about other unknown sections.

**Comment by StefanKarpinski** [comment]
Warning about other sections would be annoying if we add new sections in the future and want older versions of the package manager to gracefully handle newer versions of packages.

**Comment by KristofferC** [comment]
Yeah. Not allowing one to dump arbitrary sections in the project file would make upgrades less breaking though.

**Comment by StefanKarpinski** [comment]
True. I'm not sure if a `[ci]` section is better or worse than a separate `CI.toml` file.

**Comment by KristofferC** [comment]
I mean, I don't see why the package manager has to worry about this at all. Same as we don't have to worry about configuring CodeCov from within the project file. Any GitHub integration can use whatever interface it wants to communicate with the user, files in the repo or some setting page behind a login etc.
