### ISSUE TITLE
Cannot tab complete package names with using 

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/Pkg3.jl#161]
E.g.

```jl
pkg> add BenchmarkTools 

julia> using Ben<TAB>
```
does not complete `BenchmarkTools` as happens with `Pkg2`.

Moved from https://github.com/JuliaLang/julia/issues/26235

**Comment by fredrikekre** [comment]
Works for me

**Comment by KristofferC** [comment]
Yes, the Repl completions are not at all hooked up to the new code loading.

**Comment by StefanKarpinski** [comment]
That will be an interesting exercise.

**Comment by KristofferC** [comment]
Not too bad probably :)

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julia/pull/26246
