### ISSUE TITLE
Will Pkg3.jl support CLI?

### ISSUE THREAD

**Issue by Roger-luo** [JuliaLang/Pkg3.jl#168]
I was wondering if Pkg3.jl have plans to support CLI (Command Line Interface)? Or this will not be a Julian feature? This is not an important feature (and not hard), but I think it would be more convenient for previous `Python`, `C/C++` users who get used to shell. 

Comparing to other languages, `rust` have `cargo`, `nodejs` have `npm` and `python` have `hatch`/`pip`/`conda` etc.

**Comment by KristofferC** [comment]
It would be very simple to support (https://github.com/JuliaLang/Pkg3.jl/pull/42). The only problem is that Julia has a bit of a start-up and Pkg3 is a decently sized package so it also has a bit of overhead for the first action. With precompile statements, we can get that time down significantly but it still isn't really at the level where using it as a CLI feels good (it should be pretty much instant for that).

So, therefore, I think it might be better to have people keep a julia session open and just use that one for multiple package operations. I'll see how fast we can make the first action, and if it is fast enough, perhaps a CLI is warranted.

**Comment by Roger-luo** [comment]
I see, thanks for reply.

Will recent work on static compilation [PackageCompiler.jl](https://github.com/JuliaLang/PackageCompiler.jl) helps? I recently tried to write a [CLI Package](https://github.com/Roger-luo/CLI.jl) for this accelerates the start time a lot.

But looking forward to Pkg3. Anyways.

**Comment by KristofferC** [comment]
We don't really need PackageCompiler because Pkg3 will be in the julia sysimg and we can thus precompile statements there. Even with these, there is some delay, not too bad, but definitely not instant either.

**Comment by StefanKarpinski** [comment]
This is essentially entirely dependent on being able to compile Julia programs to fast, reasonably-sized command line tools, which is something we want to do independent of Pkg3, so I don't think we need to track it here. When that's possible, it's fairly obvious to apply it to the package manager.

**Comment by simonbyrne** [comment]
From some discussion on slack yesterday, I wrote a little script for `juliapkg`:
```
#! /usr/bin/env julia --color=yes
using Pkg
Pkg.REPLMode.pkgstr(join(ARGS,' '))
```

I've actually been using it for real work today, I have to say that combined with defining a `JULIA_PROJECT` variable, it works pretty well! The startup delay is not really noticeable.

**Comment by KristofferC** [comment]
Yeah, precompilation is pretty good now so this should actually be feasible.

**Comment by Roger-luo** [comment]
So will `Pkg` provide a CLI along with installation in the future now? 

I actually tested in iterm with `time`, for loading the module it looks faster than `pip`:

```
(julia) ➜  test git:(master) time python -c 'from pip._internal import main'
python -c 'from pip._internal import main'  0.42s user 0.19s system 73% cpu 0.819 total
(julia) ➜  test git:(master) time julia -e 'using Pkg'
julia --color=yes -e 'using Pkg'  0.19s user 0.10s system 98% cpu 0.295 total
```

@KristofferC

**Comment by KristofferC** [comment]
Well `using Pkg` is a no-op since it is in the sysimg. We could add a guide how to create your own Pkg CLI for now?

**Comment by Roger-luo** [comment]
@KristofferC Err... actually, I have one for myself, I can make a package. I'll posted the repo later here, so people who cares CLI may give me more advice.

**Comment by StefanKarpinski** [comment]
I mean, if someone (@Roger-luo maybe?) wants to build this we could certainly ship a `julia-pkg` CLI that uses the same syntax as the `pkg>` REPL mode. Why not?

**Comment by Roger-luo** [comment]
@StefanKarpinski You can't use the same syntax, since at least for `add`, 

```
add SomePackage#master
```

won't work in shell....We will need to tweak the syntax

**Comment by simonbyrne** [comment]
> ```
> add SomePackage#master
> ```
> won't work in shell

Why not? It seems to work for the [script I wrote above](https://github.com/JuliaLang/Pkg.jl/issues/168#issuecomment-422595787).

**Comment by Roger-luo** [comment]
Err... My bad, thought this was comments

**Comment by Roger-luo** [comment]
But as a CLI this won't work

```
jpm --help
```

```
jpm -h
```

We can't use `jpm ?` for help in shell.

**Comment by Roger-luo** [comment]
Okay... So I guess, if we directly install @simonbyrne 's script to `.julia/bin` folder, and if one add it to `PATH`, it will work. (despite of `activate`)

**Comment by simonbyrne** [comment]
Yes, I think you would want to manually handle --help, and for activate give a message that suggests setting the JULIA_PROJECT environment variable.

**Comment by Roger-luo** [comment]
Or start a new `shell` from julia? e.g we could have a simple shell script like `activate` (which is similar to .virtualenv's), and `julia -e 'run(`/path/to/activate PROJECT_PATH`)'` will start this new shell with the project path you pass to `Pkg`'s `activate`.

**Comment by simonbyrne** [comment]
I thought virtualenv was usually "activated" inside the existing shell (which is why you need to `source` it instead of running a different command)?

I kind of like the simplicity of just setting `JULIA_PROJECT`.

**Comment by simonbyrne** [comment]
for reference, if you want to set JULIA_PROJECT to the current directory (so that it won't change if you subsequently change directory), in bash you can do
```
export JULIA_PROJECT=$(pwd)
```
and cmd.exe you can use
```
set JULIA_PROJECT=%cd%
```

**Comment by KristofferC** [comment]
https://discourse.julialang.org/t/jlpkg-a-command-line-interface-to-pkg/24077/2
