### ISSUE TITLE
Testing the project

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Pkg3.jl#185]
Right now there is no way to test the project itself. You can test a dependency with `test Package` but you can't test the project you are currently developing. Both `test` and `test Project` should probably work where `Project` is the name of the Project (given in the `Project.toml` file).

**Comment by StefanKarpinski** [comment]
Should `pkg> test` test the current package while `pkg> test --all` tests all pacakges? Or maybe `pkg> test .` for the current package?

**Comment by KristofferC** [comment]
`test` without any argument was what I planned to implement. If you have a "named project" (`name` + `uuid` in Project.toml) then `test ProjectName` should probably also work.

**Comment by StefanKarpinski** [comment]
Yep, sounds like a good plan.

**Comment by KristofferC** [comment]
`test` and `build` now tests and build project, respectively.
