### ISSUE TITLE
REPL auto completions

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Pkg3.jl#19]
We could hook into the REPL auto completions system to provide completions when writin e.g. `free CST<TAB>` to complete it to `free CSTParser`.

**Comment by StefanKarpinski** [comment]
That's definitely part of the plan – having really good tab completion for the package repl will make this a much slicker, more pleasant UI to interact with. Tab completion can know the full syntax that's allowed too – commands, options, environments, installed packages, available packages, etc.
