### ISSUE TITLE
Short command for `up --manifest --fixed`

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Pkg3.jl#208]
This is basically, install everything that is in my Manifest as it says there. I think makes sense to have a short command for that.

**Comment by StefanKarpinski** [comment]
I guess the name is really the main question: `hydrate`, `install`, `setup`...

**Comment by KristofferC** [comment]
`realize`, `apply`...

**Comment by KristofferC** [comment]
I like `resolve`.

**Comment by StefanKarpinski** [comment]
The term "resolve" has previously been used to refer to what the version resolver does when picking a set of versions to satisfy some set of package requirements and compatibility bounds. How about `materialize`? What if we overloaded `init` to do this as well if there's are already a manifest?

**Comment by KristofferC** [comment]
`materialize` is quite descriptive. Sounds good to me.

**Comment by StefanKarpinski** [comment]
I do kind of like the idea of overloading `init` though since it is kind of an unused command otherwise.

**Comment by KristofferC** [comment]
I feel `init` could almost be removed for something like `generate --bare`

**Comment by StefanKarpinski** [comment]
But `generate` generates packages whereas `init` initializes an environment. I do have a sneaking feeling that we could do without the `init` command, however.

**Comment by KristofferC** [comment]
You gonna have to put in your docs so that everyone else knows the exact definitions of the words you're using then. `package`/ `project` / `environment` etc.

**Comment by davidanthoff** [comment]
``clone`` already means something else, right? I like ``init`` better than ``materialize``. Does npm use ``install`` for that?

**Comment by ssfrr** [comment]
`generate --env myenv` to generate a named environment?

**Comment by StefanKarpinski** [comment]
There's not much generated to create a named environment – you just create the directory and touch the project file.

**Comment by KristofferC** [comment]
Which is why I wanted to call it create or new.

**Comment by ssfrr** [comment]
> There's not much generated to create a named environment – you just create the directory and touch the project file.

I was :+1:ing @KristofferC's suggestion to merge `generate` and `init`, except with the argument `--env` rather than `--bare`, just so there's one fewer term to define ("bare project" vs "environment").

Though there might not be much involved with initializing an environment, it seems like it's useful to have a Pkg3 command rather than having users use `mkdir` and `touch`.

**Comment by KristofferC** [comment]
`instantiate`?

**Comment by StefanKarpinski** [comment]
I know I haven't really convinced people that the notion of "environment" separate from "project" makes sense, but I still believe that it does even though it's somewhat abstract. Here are a list of things that induce an environment:

1. A project
2. A Pkg2-style package directory with entry points in it like `X/src/X.jl`
3. A stack of environments defines a new overlayed, composite environment

The environment you're working in at any given point is a "stacked" environment including every environment found in your load path. The current project will typically be *first* in this stacked environment, but unless there's nothing else in your load path, that will not be the full environment.
