### ISSUE TITLE
Does Pkg3 not respect JULIA_PKGDIR env variable?

### ISSUE THREAD

**Issue by quinnj** [JuliaLang/Pkg3.jl#216]
I started julia this morning and did `pkg> develop CSV`, which installed CSV + all dependencies to `~/.julia/`, even though I have `JULIA_PKGDIR=/home/chronos/user/Downloads/.julia`. Doing `using CSV` at the repl then ended up w/ a an error like `Module Missings not found in current path`, even though it indeed was installed to `~/.julia/packages`.

I'm not quite sure what's going on here, but I'm guessing my `JULIA_PKGDIR` is messing things up somehow?

**Comment by StefanKarpinski** [comment]
`JULIA_PKGDIR` is going to go away in 1.0 but is currently somewhat supported by having `Pkg.dir` in `LOAD_PATH`. What package is it that's trying to load `Missings` and not finding it?

**Comment by KristofferC** [comment]
The problem was CSV not declaring a dependency on `Missings` (see pkg in slack)

**Comment by StefanKarpinski** [comment]
Ah, so this is actually Pkg3 finding a bug in a package rather than a Pkg3 issue. Nice 😁

**Comment by quinnj** [comment]
Well, it would certainly be nice if Pkg3 could help the package dev out here instead of just saying it couldn't find a package dep that's clearly there/installed. As my first experience using Pkg3, it was a little frustrating not knowing why things weren't working.

**Comment by polytomous** [comment]
@quinnj I've been working on some Lua<->Julia binding code, and I really enjoyed how LuaJit will list out all of the locations it looks for a given package on a failed `require("package")` call. Something similar would help here in the case where you had a differing path configuration, and would also help isolate issues in nested/differing path configs. Would you want to pair on a prototype? I use julia roughly like you so I need to figure this out for myself! 😺 I'm spending today getting familiar with pkg3 / julia .7

**Comment by StefanKarpinski** [comment]
The error messages definitely need much improvement – I pretty much kept the errors the same from Julia 0.6 and they often don't make much sense in the new world order. This is not actually a Pkg3 issue since the code loading is part of Base Julia.

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julia/issues/26472

**Comment by KristofferC** [comment]
Why not set `JULIA_PROJECT` env variable? Which is unfortunately yet undocumented heh... It sets active project on startup.

**Comment by rofinn** [comment]
Nice! Thanks, that makes life a lot easier :)

**Comment by StefanKarpinski** [comment]
`DEPOT_PATH[1]` is where everything gets written so if you want to do all of that in a temporary place you can do something like `mktempdir() do dir; push!(DEPOT_PATH, dir); ...; end`.
