### ISSUE TITLE
Pkg.test

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Pkg3.jl#22]
Since Pkg is going away, something need to be done with `Pkg.test`.

There are a few options:

* Just move it to Pkg3. Easiest, and I haven't seen that many complaints about the testing. Of course people want to be able to run it in parallel and do more fine grained stuff but it is not a major source of complaints.
* Replace it with a new, better interface that can run stuff in parallel, have options etc. 

Perhaps the simplest way forward is just to move Pkg.test here and then let external testing packages develop, and if/when one of them mature to the point that it is clearly better, consider it for inclusion in Base.

**Comment by StefanKarpinski** [comment]
I think the first step is just to duplicate existing `Pkg.test` as a `pkg> test` command. Behavior: by default (no arguments) test all packages in the current manifest; if names are given test those packages and their dependencies; maybe a `--deps=[no|yes]` option to control whether or not to test dependencies or not. Does that seems like a sane interface? Want to work on it?

**Comment by KristofferC** [comment]
Why would you want to test the dependencies of your package? Presumably you are working under the assumption that those are working correctly?

**Comment by StefanKarpinski** [comment]
To see if everything is working. How would you expect it to work?

**Comment by KristofferC** [comment]
Same as `Pkg.test("Package")` works except it is spelled `pkg> test Package`

**Comment by StefanKarpinski** [comment]
Ok, fair enough. In that case there should be a `[-r|--recursive]` option that tests all recursive dependencies of the listed packages as well. What would `pkg> test` by itself do? Maybe `pkg> test` can test the current project? Then `pkg> test -r` would be a natural way to test everything.

We probably also want to think a bit about syntax for filtering tests, but maybe that can wait for another day. `pkg> test --filter=...` comes to mind, applying to all the following package names.

**Comment by KristofferC** [comment]
Recursive dependency testing is a good idea.

Getting to feature parity with Pkg2 (being able to just test one package) seems like a good starting point.

**Comment by KristofferC** [comment]
Implemented the basic stuff now, what is lacking to get up to Pkg2.test is to resolve the dependencies and test only dependencies and for that we need to determine how a package should store that information.

**Comment by tpapp** [comment]
Will one be able to use this framework for "local" packages? Currently I am using a [hack](https://github.com/tpapp/RoguePkg.jl) for this, and I was hoping this would be obsoleted by `Pkg3`; or lacking that, some hook would be available to maintain this functionality.

**Comment by KristofferC** [comment]
Yes, this will work with local packages. There is no difference really. Test-dependencies are now supported.
