### ISSUE TITLE
Wrong version range for AbstractFFTs 0.3+ in Uncurated registry

### ISSUE THREAD

**Issue by martinholters** [JuliaLang/Pkg3.jl#231]
(I hope I'm correct to report issues in the automated `METADATA` to `Uncurated` translation here.)

AbstractFFTs 0.3.0 and 0.3.1 have the Julia version requirement
```
julia 0.6 0.7.0-DEV.602 0.7.0-DEV.3449
```
I.e. the package should not be installable on Julia versions `0.7.0-DEV.602` (inclusive) to `0.7.0-DEV.3449` (exclusive), but newer Julia versions are ok. However, it gets translated to
```
["0.3"]
julia = "0.6"
```
This makes these versions uninstallable on current Julia master.

**Comment by KristofferC** [comment]
Yeah, this is the correct place.

I think the problem is https://github.com/JuliaLang/Pkg3.jl/blob/be61572367138150306eda2f18f5f9dab427bb06/bin/loadmeta.jl#L38-L40

**Comment by martinholters** [comment]
Ah, so that would have to iterate over all `r.versions.intervals` and union them I guess? But why is the `-DEV` part omitted?

**Comment by martinholters** [comment]
Does this make sense? 
```diff
diff --git a/bin/loadmeta.jl b/bin/loadmeta.jl
index 032b274..57ac0f6 100644
--- a/bin/loadmeta.jl
+++ b/bin/loadmeta.jl
@@ -7,12 +7,12 @@ import Pkg3
 using Pkg3.Types
 using Pkg3.Types: uuid_package, uuid_registry, uuid5
 import Pkg3.Pkg2.Reqs: Reqs, Requirement
-import Pkg3.Pkg2.Pkg2Types: VersionInterval
+import Pkg3.Pkg2.Pkg2Types: VersionInterval, VersionSet
 
 ## Loading data into various data structures ##
 
 struct Require
-    versions::VersionInterval
+    versions::VersionSet
     systems::Vector{Symbol}
 end
 
@@ -27,7 +27,8 @@ struct Package
     versions::Dict{VersionNumber,Version}
 end
 
-Require(versions::VersionInterval) = Require(versions, Symbol[])
+Require(versions::VersionSet) = Require(versions, Symbol[])
+Require(version::VersionInterval) = Require(VersionSet([version]), Symbol[])
 Version(sha1::String) = Version(sha1, Dict{String,Require}())
 
 function load_requires(path::String)
@@ -35,9 +36,8 @@ function load_requires(path::String)
     requires["julia"] = Require(VersionInterval())
     isfile(path) || return requires
     for r in filter!(r->r isa Requirement, Reqs.read(path))
-        # @assert length(r.versions.intervals) == 1
         new = haskey(requires, r.package)
-        versions, systems = r.versions.intervals[1], r.system
+        versions, systems = VersionSet(r.versions.intervals), r.system
         if haskey(requires, r.package)
             versions = versions ∩ requires[r.package].versions
             systems  = systems  ∪ requires[r.package].systems
diff --git a/bin/utils.jl b/bin/utils.jl
index 4a84f6a..f8f7c11 100644
--- a/bin/utils.jl
+++ b/bin/utils.jl
@@ -50,6 +50,8 @@ compress_versions(f::Function, from::Vector{VersionNumber}) =
     compress_versions(filter(f, from), from)
 compress_versions(vi::VersionInterval, from::Vector{VersionNumber}) =
     compress_versions(v->v in vi, from)
+compress_versions(vs::VersionSet, from::Vector{VersionNumber}) =
+    compress_versions(v->v in vs, from)
 compress_versions(inc, from) = compress_versions(inc, collect(from))
 
 versions_string(p::Pair) = versions_string(p...)
```
Seems to work for me locally, except that I get
```
[ Info: Updating NanoTimes from https://github.com/JeffreySarnoff/NanoTimes.jl.git
ERROR: LoadError: LoadError: NanoTimes: git object f887ea730974ed97287d05a8acf541367206cb24 could not be found
Stacktrace:
 [1] error at ./error.jl:33 [inlined]
 [2] gitmeta(::Dict{String,Package}) at /home/hol/Pkg3.jl/bin/gitmeta.jl:93
```
If I add `NanoTimes` to the list of packages to be deleted from `pkgs`, everything seems to be ok AFAICT.

**Comment by StefanKarpinski** [comment]
> But why is the `-DEV` part omitted?

The bounds are only for versions that are registered — `0.7.0-DEV.3449` us not registered. I'm not really sure that we should support registering pre-release versions. After all, they are "pre release" and anything that's registered has been released.

**Comment by marius311** [comment]
Hi guys, is there a workaround to get this to work, since currently I can't install AbstractFFTs >0.2.1, meaning no FFTW >0.2.0 and hence no working `plan_fft` on 0.7?

**Comment by marius311** [comment]
Nevermind, found one (for anyone wishing to hack together a working environment to play around with). You can change `.julia/registries/Uncurated/A/AbstractFFTs/Compat.toml` to read eg.

```
["0.0-0.2"]
julia = "0.6-0.7"

["0.3"]
julia = "0.6-0.7"
```

**Comment by martinholters** [comment]
Did you take a look? I might find some time to pick up from where I left, but wouldn't want to duplicate any work you might have done in the meantime.

**Comment by KristofferC** [comment]
Sorry, no I didn't do anything yet. If you have some time over it would be great if you could try it more and I'll work on some other stuff in the meantime :)

**Comment by martinholters** [comment]
Um, ok, the failure for NanoTimes I'm seeing seems to be unrelated to the patch. The old METADATA has the single version 0.0.1 pointing to commit f887ea730974ed97287d05a8acf541367206cb24. However, n https://github.com/JeffreySarnoff/NanoTimes.jl, I can find neither v0.0.1 nor that commit. In fact, the commits there seem to start on March 22, 2018, while v0.0.1 was released on Oct 24, 2017 (https://github.com/JuliaLang/METADATA.jl/pull/11720). And using the old "Pkg.add("NanoTimes")", I'm also seeing
```
ERROR: Missing package versions (possible metadata misconfiguration):  NanoTimes v(nothing, v"0.0.1") [f887ea730974ed97287d05a8acf541367206cb24[1:10]]
```
@JeffreySarnoff, did you do something funny with that repository?

So I guess the best solution would be to reconstruct the missing commit in the repository if possible, and otherwise remove the entry from METADATA?

**Comment by KristofferC** [comment]
For now, I have locally added:

```
+    "NanoTimes"
+    "ProjectiveDictionaryPairLearning"
+    "React"
+    "Sparrow"
```

to 

https://github.com/JuliaLang/Pkg3.jl/blob/bd3802f3738c834f44ccb2d354b2befb0cea4234/bin/loadmeta.jl#L147-L156

**Comment by martinholters** [comment]
Ok, good to know, then I'll do the same :smile:

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/Pkg3.jl/pull/285

**Comment by JeffreySarnoff** [comment]
@StefanKarpinski can you just remove NanoTimes from Metadata?

**Comment by StefanKarpinski** [comment]
No, once something is published, it must be reproducible in the future. If you publish something, it should not be deleted; in the future we'll have a mechanism to keep copies of registered packages around even when the author abandons or deletes them, but we don't yet have such a mechanism.

**Comment by JeffreySarnoff** [comment]
Ok -- 
right now there is no v0.0.1 of NanoTimes (though there once was, it seems).
I can just copy TimesDates into NanoTimes and register that as [a replacement] v0.0.1 (does that work)
