### ISSUE TITLE
Pkg3 readme instructions say to clone from broken commit

### ISSUE THREAD

**Issue by 0joshuaolson1** [JuliaLang/Pkg3.jl#236]
The readme on the default branch (`master`) links to the latest working commit.

`Pkg.clone` fetches `HEAD` from the default branch, right?

**Comment by KristofferC** [comment]
Yeah, the readme is quite outdated. I opened #237 for this.

**Comment by 0joshuaolson1** [comment]
It's moving out of alpha? Awesome!

**Comment by KristofferC** [comment]
Well, I guess it is in a superposition between alpha and beta heh.

**Comment by StefanKarpinski** [comment]
It's in "balpha".
