### ISSUE TITLE
Progress bar spams CI

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Pkg3.jl#241]
![screen shot 2018-04-06 at 16 35 14](https://user-images.githubusercontent.com/1282691/38427241-020c7630-39b9-11e8-800b-ed4455203ed8.png)

Should probably disable on CI or when non-interactive or something like that.

**Comment by Keno** [comment]
The canonical solution here is to rate limit the progress to 1Hz or sth of that nature.

**Comment by KristofferC** [comment]
I want my 60 fps ;).

I wish there was an easy way to detect if the output supports `\r`.

**Comment by pfitzseb** [comment]
CI doesn't run with `-i`, so checking for `isinteractive()` might do the trick?

**Comment by KristofferC** [comment]
Yeah but if you run something like `julia -e 'import Pkg3; Pkg3.add("Example")'` you probably want to see it even though you are not running in interactive mode.

**Comment by pfitzseb** [comment]
That could fall back to a simpler implementation like
```
     Fetching: [...       ]
```
though. Detecting a terminal's support for escape codes is a pretty difficult problem afaict; one might be able to use [`\e[6N`](https://en.wikipedia.org/wiki/ANSI_escape_code) for this, but it definitely wouldn't be pretty...
