### ISSUE TITLE
What should free do?

### ISSUE THREAD

**Issue by fredrikekre** [JuliaLang/Pkg3.jl#266]
Consider a package that is pinned to something that is not a version:
```
pkg> add Tensors#master

pkg> pin Tensors
```

Now, `pkg> free Tensors` does two things: (1) unpin and (2) jump to the latest release, i.e. `v0.7.3`.

I propose that this should require two `free` calls: `pkg> free Tensors` should first just unpin and track `#master` and the next `pkg> free Tensors` should jump to the latest version. The rule about what `free` does would then be pretty simple:

- If the package is `pin`ned, then we unpin
- If the package is tracking something that is not a version, then we jump to a version.

**Comment by KristofferC** [comment]
I think this makes sense.
