### ISSUE TITLE
Wrong tree-SHA for RecipesBase?

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Pkg3.jl#276]
```
(Pkg3) pkg> add RecipesBase
[ Info: Pkg3 is still under development, please file issues at `https://github.com/JuliaLang/Pkg3.jl`.
┌ Info: Pkg3 is running without precompile statements, first action will be slow.
│ Rebuild julia with the environment variable `JULIA_PKG3_PRECOMPILE` set to enable precompilation of Pkg3.
└ This message can be disabled by setting the env variable `JULIA_PKG3_DISABLE_PRECOMPILE_WARNING`.
  Updating registry at `~/.julia/registries/Uncurated`
  Updating git-repo `https://github.com/JuliaRegistries/Uncurated.git`
 Resolving package versions...
┌ Warning: project file for Compat is missing a `version` entry
└ @ Pkg3.Operations Operations.jl:143
ERROR: RecipesBase: git object 7914cf297f96ebef3d4e6531a7dd0694bada0959 could not be found
```

**Comment by KristofferC** [comment]
Plots guys rebased their branch they made the release commit from.

**Comment by simonbyrne** [comment]
where did that come from? The METADATA one is different: https://github.com/JuliaLang/METADATA.jl/blob/metadata-v2/RecipesBase/versions/0.3.0/sha1

**Comment by simonbyrne** [comment]
oh right, that's a commit vs tree hash

**Comment by simonbyrne** [comment]
What's the plan for this sort of thing? I could see this becoming an issue, e.g. if someone accidentally tags a release containing personal data?

**Comment by KristofferC** [comment]
If you just want to disable a release because it was somehow faulty, in my view we could easily add a `retracted` field to a version in the registry and not consider that during resolution. Instantiating existing manifests that uses this version would still continue to work though. I think that is how Cargo does it.

Regarding your question, do you mean that the release itself (that might have been downloaded by many people) contained sensitive information?

**Comment by simonbyrne** [comment]
Yes, and also what happens if a package maintainer simply deletes the data from the repository (or indeed the whole repository)?

**Comment by simonbyrne** [comment]
It is worth thinking a bit about a retraction mechanism, as I'm sure it will be necessary at some point.

**Comment by KristofferC** [comment]
In order to retract sensitive information or just not have people install a buggy release?

**Comment by KristofferC** [comment]
This seems fixed now.

**Comment by simonbyrne** [comment]
> In order to retract sensitive information or just not have people install a buggy release?

I was thinking about sensitive information, or possibly illegal content, but we may also want to have a way to stop known buggy releases.
