### ISSUE TITLE
Rebuilding packages that failed to build

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Pkg3.jl#31]
Is there such a functionality right now? It is likely needed, right?

**Comment by StefanKarpinski** [comment]
Probably, yes. Although hopefully BinDeps2 will end up eliminating all building.

**Comment by vdayanand** [comment]
This is needed, while creating JuliaPro installer, for Jupyter dependent packages. For this, I have a `build` function which uses DFS  to get the uuids and later calls `build_versions`. Is there any other approach planned?

**Comment by KristofferC** [comment]
I think having a `build` command that optionally takes a package is a good way. Similar as `Pkg.build` works now. While BinDeps2 might remove some building, the building framework is also used to set some global options for a package so I think we still need this functionality.

**Comment by StefanKarpinski** [comment]
🎉 ❤️
