### ISSUE TITLE
Stop auto creating Manifests + Projects in git repos

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Pkg3.jl#40]
After using Pkg3 for a while, this is quite annoying. I think one should explicitly have to instantiate these using some `init` command. If it is a git repo, we go to the base, otherwise just in the cwd.

**Comment by lobingera** [comment]
@KristofferC Could you provide some context? In which git repos?

**Comment by KristofferC** [comment]
In git repos that happens to be in your current working directory.

**Comment by StefanKarpinski** [comment]
I commented in my review of https://github.com/JuliaLang/Pkg3.jl/pull/51#discussion_r153489270:

> Different scenario: what if you have `JULIA_ENV` set to a name like `v1.2.3` and `~/.julia/environments/v1.2.3` does not yet exist. Should this create those files? In that case it's more reasonable to just auto-create the directory and its project and manifest files. But what if someone explicitly does `pkg> init` in those circumstances? Or maybe all environments should be explicitly created...

Perhaps auto-discovery of the current environment is too clever. In Python virtualenv, you have to explicitly set your environment. Should we do something more like that? I do think this design makes it easy to hop back and forth between projects in a single terminal session, which is nice.

But this whole environment discovery step could use a little thought.
