### ISSUE TITLE
Update the registry on update

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Pkg3.jl#48]
How often should the registry be updated? Every time we run something that needs to resolve, should there be a "grace period" between registry updates etc?

Thoughts?

**Comment by StefanKarpinski** [comment]
Did you make a decision here?

**Comment by KristofferC** [comment]
Right now it is every time on update.

**Comment by StefanKarpinski** [comment]
That seems reasonable. There should probably be a way to just update registries and all upstream that have any versions that we don't know about so that you can do that before e.g. getting on a plane and then be able to update your software locally, but that's a future feature.
