### ISSUE TITLE
up/down keys don't work inside ansi-term in Emacs

### ISSUE THREAD

**Issue by tpapp** [JuliaLang/Pkg3.jl#61]
Eg in a context of
```julia
julia> using JLD2
Could not find package JLD2, do you want to install it?
 > yes
   yes (remember)
   no
   no (remember)
```
At the same time, the same terminal handles up/down keys for the REPL fine.

**Comment by KristofferC** [comment]
I don't think this is a Pkg3 issue. Since it works in the Julia REPL it seems that whatever is done in emacs is failing to emulate that. Also, these menus are from https://github.com/nick-paul/TerminalMenus.jl.
