### ISSUE TITLE
The `verb` argument in `package_env_info` is unused.

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Pkg3.jl#71]
https://github.com/JuliaLang/Pkg3.jl/blob/3b8d98be0d43fce884d544ee0d4c6b6ee833d900/src/Operations.jl#L50

**Comment by StefanKarpinski** [comment]
I have a PR somewhere to delete that function entirely, but it got stalled. Used to be used in more places, but now I think only in the one place. Feel free to refactor however you like!

**Comment by KristofferC** [comment]
Deleted
