### ISSUE TITLE
OVerflow problem

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Pkg3.jl#72]
The following conversion can (silently) overflow when dealing with `typemax(VersionNumber)`, for example when a package has no upper bound.

https://github.com/JuliaLang/Pkg3.jl/blob/d335252ae8ea39b383daeb96217d6d8d3405e822/src/Types.jl#L137-L138

Could you explain the reason for the `+1` @StefanKarpinski

**Comment by StefanKarpinski** [comment]
Ah, it's because `VersionSet` (and Pkg2 in general) uses non-inclusive upper bounds while `VersionRange` (and Pkg3 in general) uses far-less-confusing inclusive upper (and lower) bounds. So the fix here would seem to be to replace `r.upper[3]+1` with `max(r.upper[3], r.upper[3]+1)`.
