### ISSUE TITLE
Operation.init_if_interactive interrupts Base.edit

### ISSUE THREAD

**Issue by vdayanand** [JuliaLang/Pkg3.jl#95]
`_find_package`  is used by Base.edit to search the source file. This function is also overridden by Pkg3, and when JULIA_ENV is set and not initialized,  `Operations.init_if_interactive` interrupts.

```
julia> import Pkg3
julia> Base.edit(isfile, [String])
Could not find local environment in /home/osboxes/temp/Project.toml, do you want to create it?
 > yes
   no
```

**Comment by KristofferC** [comment]
Not applicable anymore.
